{
    'name': "Manager cost",
    'summary': """Manager cost module""",
    'description': """Manager cost module""",
    'author': "manh",
    'website': "https://www.facebook.com/hayhaayhay/",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': ['base','hr',
    ],
    'data': [
        'views/staff2_views.xml',
        'views/rule_views.xml',
        'views/revenue_2_views.xml',
        'security/ir.model.access.csv',
        'data/auto_send_mail_2.xml',
        'data/mail_template_2.xml',
        'views/purchase_views.xml',
        'views/detail_purchase_views.xml',
    ],
    # 'qweb': ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,
}